config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :users, :only => [:show]
 
resources :events do
  resources :event_attendees, :only => [:create,:destroy]
end
resources :categories  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name,presence:true,uniqueness: true
    belongs_to :creator, class_name: 'User'
    has_many :event_categories,foreign_key: :category_id,dependent: :destroy
    has_many :events , through: :event_categories, source: :event
end

app/models/event.rb
class Event < ApplicationRecord
    validates :name,presence:true
    validates :creator_id,presence:true
    validates :description,presence:true
    validates :e_date,presence:true
    belongs_to :creator, class_name: 'User'
    has_many :event_attendees,foreign_key: :event_id,dependent: :destroy
    has_many :attendees , through: :event_attendees, source: :attendee
    has_many :event_categories,foreign_key: :event_id
    has_many :categories,through: :event_categories,source: :category
    def self.past
        return self.all.where("e_date < ?",Time.now)
    end    
    def self.upcoming
        return self.all.where("e_date >?",Time.now)
    end
end

app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
    belongs_to :event ,class_name: "Event"
    belongs_to :attendee, class_name: "User"
end

app/models/event_category.rb
class EventCategory < ApplicationRecord
    belongs_to :event ,class_name: "Event"
    belongs_to :category, class_name: "Category"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates_presence_of :firstname,:lastname
  has_many :events , foreign_key: :creator_id ,class_name: 'Event',dependent: :destroy
  has_many :categories , foreign_key: :creator_id ,class_name: 'Category',dependent: :destroy
  has_many :event_attendees,foreign_key: :attendee_id
  has_many :attended_events,through: :event_attendees,source: :event
  def attended?(event)
    if EventAttendee.where(attendee_id:self.id,event_id:event.id).exists?
      return true
    else return false
    end
  end
  def full_name
    "#{firstname} #{lastname}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname,:lastname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:firstname,:lastname])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!

    def index
        @categories = Category.all
    end
    def new
        @category = Category.new
    end
    def create
    @category= current_user.categories.build(category_params)
   
     if @category.save 
       redirect_to categories_path
      
     else 
      render 'new'
     end
  end 
    def destroy
    end
   def show
    @category = Category.find(params[:id])
    @events = @category.events
   end 
private
def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
before_action :set_event
    def create
       
        @event_attendee = EventAttendee.new(attendee_id:current_user.id,event_id:@event.id)
        if @event_attendee.save
            flash[:notice]= "Attended Successfully"
            redirect_to @event
            
        end    

    end
    def destroy
        @event_attendee = EventAttendee.find_by(attendee_id:current_user.id,event_id:@event.id)
        @event_attendee.destroy
        flash[:alert]="Left Event"
        redirect_to @event
    end  
      
    private
     def set_event
        @event = @event= Event.find(params[:event_id])
     end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!,except: [:index]
  def index
    @events = Event.all
    @previous_events = Event.past
    @upcoming_events = Event.upcoming
  end
  def create
    @event= current_user.events.build(event_params)
    @fullname = "#{current_user.firstname} #{current_user.lastname}"
     if @event.save 
        if params[:event][:attendee_ids].present?
          params[:event][:attendee_ids].each do |attendee|
            EventAttendee.new(attendee_id:attendee,event_id:@event.id).save
          end
        end 
        if params[:event][:category_ids].present?
          params[:event][:category_ids].each do |category|
            EventCategory.new(category_id:category,event_id:@event.id).save
          end
        end 
       redirect_to @event
      
     else 
      render 'new'
     end
  end 
  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
     
      redirect_to @event
    
    else
      render 'edit'
    end
  end 

  def new
    @event = Event.new

  end
  def show 
    @event= Event.find(params[:id])
  end  
  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:alert]= "Event Deleted"
    redirect_to root_path
  end
 private 
 
  def event_params
    params.require(:event).permit(:name,:description,:e_date,:attendee_ids,:category_ids)
  end
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user= User.find(params[:id])
        @events= @user.events.all
        @attended_events = @user.attended_events
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active_class(path)
        if request.path == path
          return 'active'
        else
          return ''
        end
      end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<li>
<%= link_to category.name,category %>
</li>

app/views/categories/index.html.erb
<h1>Categories : </h1>
<%= render @categories %>
<%= link_to "New Category",new_category_path,class:"btn btn-primary"%>

app/views/categories/new.html.erb
<%= form_with(model: @category,local: true, data: { turbo: false }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control' %>
</div>



<div class="form-group">
<%= f.submit "Add Category" , class:"btn btn-primary"%>
</div>
<%end%>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<ul>
<%= render @events %>
</ul>

app/views/events/_event.html.erb
<li><%=link_to event.name , event %>
</li>

app/views/events/edit.html.erb
<%= form_with(model: @event,local: true, data: { turbo: false }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :description %>
<%= f.text_area :description, autofocus: true, autocomplete: 'description', class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :date %>
<%= f.date_field :e_date, autofocus: true, autocomplete: 'e_date', class: 'form-control' %>
</div>
<div class="form-group">
<%= f.submit "Update Event" , class:"btn btn-primary"%>
</div>
<%end%>

app/views/events/index.html.erb
<div style="margin:20px">
<h2>Previous Events:</h2>
<%= render @previous_events %>
<h2>Upcoming Events:</h2>
<%= render @upcoming_events %>
</div>
<%= link_to "Create Event" ,  new_event_path,class:"btn btn-primary" %>

app/views/events/new.html.erb
<%= form_with(model: @event,local: true, data: { turbo: false }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true, autocomplete: 'name', class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :description %>
<%= f.text_area :description, autofocus: true, autocomplete: 'description', class: 'form-control' %>
</div>
<div class="form-group">
<%= f.label :date %>
<%= f.date_field :e_date, autofocus: true, autocomplete: 'e_date', class: 'form-control' %>
</div>

<div class="form-group">
<label for="event_Attendees">Attendees</label>
<input name="event[attendee_ids][]" type="hidden" value="" autocomplete="off">
<select multiple="multiple" size="4" name="event[attendee_ids][]" id="event_attendee_ids">
<% User.where.not(id: current_user.id).each do |user| %>
<option value=<%= user.id %>><%= user.firstname %> <%= user.lastname %></option>
<%end %>
</select>

</div>
<div class="form-group">
<%= f.label :Categories %>
<%= f.select :category_ids, options_from_collection_for_select(Category.all, :id, :name , {:selected => @event.category_ids.split(';')}), {}, {:multiple => true, :size => 4, :name => 'event[category_ids][]'} %>
</div>
<div class="form-group">
<%= f.submit "Add Event" , class:"btn btn-primary"%>
</div>
<%end%>

app/views/events/show.html.erb
<h2><%= @event.name %></h2>
<h4>Description:</h4>
<p><%= @event.description %></p>
<p><strong>Date :</strong> <%= @event.e_date %></p>
<p>Created by: <%= @event.creator.firstname %> <%= @event.creator.lastname %></p>
<%= link_to "Edit", edit_event_path(@event) if current_user == @event.creator %> |
<%= link_to "Delete", event_path(@event),method: :delete if current_user == @event.creator %>
<h4>Attendees:</h4>
<% if @event.attendees.any? %>
<ul>

<% @event.attendees.each do |attendee| %>
    <li><%= link_to "#{attendee.firstname} #{ attendee.lastname}", attendee %></li>
    <%end%>
</ul>

<%else%>
<p>No attendees yet</p>
<%end%>
<% if @event.categories.any? %>
<h4>Categories:</h4>
<ul>

<% @event.categories.each do |category| %>
    <li><%= link_to category.name, category %></li>
    <%end%>
</ul>
<%end%>
<% unless current_user == @event.creator %>
<% unless  current_user.attended?(@event) %>
<%= button_to "Attend" , event_event_attendees_path(@event) ,class:"btn btn-primary",method: :post, disabled:  current_user.attended?(@event)%>
<%else%>
<%= button_to "Leave" , event_event_attendee_path(@event) ,class:"btn btn-primary",method: :delete, disabled:  !current_user.attended?(@event) %>
<%end%>
<% end %>
<%= link_to "Back", root_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" >
  <div class="container-fluid">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path , class:"navbar-brand" do %>
        Events
        <%end%>
    </div>

    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <%= yield :right_nav %>
        <li><%= link_to "Categories", categories_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%=current_user.firstname %> <%=current_user.lastname %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li role="separator" class="divider"></li>
            <li><%= link_to "Settings", edit_user_registration_path %></li>
          
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: "layouts/navbar" %>
  <% if notice %>
  <p class="alert alert-success" style="padding-top:70px"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger" style="padding-top:70px"><%= alert %></p>
<% end %>

<div class="container" style="padding-top:50px">
    <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
<div class="alert alert-danger" >
The form contains <%= pluralize(object.errors.count, "error") %>.
</div>
<ul>
<% object.errors.full_messages.each do |msg| %>
<li style="color:red"><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

app/views/users/show.html.erb
<h4><%= @user.firstname %> <%= @user.lastname%></h4>

<br/>

<h4><%= @user == current_user ? "My Events" : "#{@user.firstname}'s Events" %> : </h4>

<%= render @events %>

<h4>Previous Events:</h4>
<ul>
<% @attended_events.where("e_date < ?",Time.now).each do |event| %>
    <li><%= link_to event.name , event %> </li>
    <%end%>
</ul>
<h4>Upcoming Events:</h4>
<ul>
<% @attended_events.where("e_date > ?",Time.now).each do |event| %>
    <li><%= link_to event.name , event %> </li>
    <%end%>
</ul>